#!/usr/bin/env bash
# Script Name   : install
# Author        : Sébastien Gordano
# Date          : 07/2023
# Version       : 1.0
# Usage         : bash install
# Description   : Install / configure the basics for the use of WM on Arch linux
#===========================================================================
printf "
   ___                  _                 
  / _ \ _ __   __ _  __| |_ __ ___   __ _ 
 | | | | '_ \ / _' |/ _' | '__/ _ \ / _' |
 | |_| | | | | (_| | (_| | | | (_) | (_| |
  \___/|_| |_|\__,_|\__,_|_|  \___/ \__, |
       | | | | ___| |_ __   ___ _ __|___/ 
       | |_| |/ _ \ | '_ \ / _ \ '__|     
       |  _  |  __/ | |_) |  __/ |        
       |_| |_|\___|_| .__/ \___|_|        
                    |_|                   \n"
printf "Oi mate, Welcome to Onadrog's helper !\n\n"
printf 'Are ya running a laptop ?\n'
PS3='Make a choice (e.g. 1): '
options=("Yes" "No")

select opt in "${options[@]}"
do
    case $opt in
        "Yes")
            is_laptop="$opt"
            break;
            ;;
        "No")
            is_laptop="$opt"
            break
            ;;
        *) echo "Invalid choice";;
  esac
done



#############################################
#                WM CHOICE                  #
#############################################
printf "
  ____  _      _                                           _                 
 |  _ \(_) ___| | __  _   _  ___  _   _ _ __   _ __   ___ (_)___  ___  _ __  
 | |_) | |/ __| |/ / | | | |/ _ \| | | | '__| | '_ \ / _ \| / __|/ _ \| '_ \ 
 |  __/| | (__|   <  | |_| | (_) | |_| | |    | |_) | (_) | \__ \ (_) | | | |
 |_|   |_|\___|_|\_\  \__, |\___/ \__,_|_|    | .__/ \___/|_|___/\___/|_| |_|
                      |___/                   |_|                            \n"

PS3='Make a choice(e.g. 1): '
options=("sway" "hyprland")

select opt in "${options[@]}"
do
    case $opt in
        "sway")
            wm="$opt"
            break;
            ;;
        "hyprland")
            wm="$opt"
            break
            ;;
        *) echo "Invalid choice";;
  esac
done

#############################################
#               BASIC INSTALL               #
#############################################

sudo pacman -Syu --noconfirm \
    brightnessctl vlc streamlink \
    playerctl neovim reflector \
    cups docker util-linux \
    ufw keepassxc swaylock swayidle \
    base-devel nodejs npm pnpm \
    pcmanfm waybar \
    wl-clipboard otf-font-awesome gammastep \
    dnscrypt-proxy chezmoi \
    polkit-kde-agent firefox wofi \
    htop lightdm lightdm-gtk-greeter \
    rsync foot
   
if [ "$is_laptop" == "Yes" ]; then
    sudo -S --noconfirm tlp upower
fi

if [ "$wm" == "sway" ]; then
    sudo pacman -S --noconfirm \
        sway xdg-desktop-portal-gtk \
        xdg-desktop-portal-wlr swaybg
else
    sudo pacman -S --noconfirm \
        hyprland qt5-wayland xdg-desktop-portal-hyprland \
        hyprpaper
fi

#############################################
#             INSTALL AUR HELPER            #
#############################################
printf "Would you like to install an AUR helper ?
"
PS3='Make a choice: (e.g. 1): '
options=("Yes" "No")

select opt in "${options[@]}"
do
    case $opt in
        "Yes")
            want_aur="$opt"
            break
            ;;
        "No")
            want_aur="$opt"
            break;;
    esac
done

if [ "$want_aur" == "Yes" ]; then
    printf "Choose an AUR helper from the list: \n"
    PS3='Make a choice: (e.g. 1): '
    options=("yay" "paru") 

    select opt in "${options[@]}"
    do
        printf 'Installing %s helper\n' "$opt"
        sudo pacman -S --noconfirm --needed base-devel
        git clone https://aur.archlinux.org/"${opt}".git
        cd "$opt" || exit
        makepkg -si
        printf '%s installed\n' "$opt"
        cd || exit
        break;
    done

fi

#############################################
#               DNSCRYPT SERVICES           #
#############################################


sudo printf "nameserver 127.0.0.1
nameserver ::1
options edns0
" | tee /etc/resolv.conf && chattr +i /etc/resolv.conf

#############################################
#               SYSTEMD SERVICES            #
#############################################

printf 'Enabling systemd services...\n'

sudo systemctl enable reflector.timer cups.service fstrim.service docker.service ufw.service NetworkManager.service dnscrypt-proxy.service lightdm.service

if [ "$is_laptop" == "Yes" ];
then
  sudo systemctl enable tlp upower
fi

#############################################
#                CONF SHELL                 #
#############################################

printf "alias clean='sudo pacman -Qtdq | sudo pacman -Rns -'
export EDITOR='nvim'
" | tee ~/.bashrc

#############################################
#            COPY CONF FILES                #
#############################################

rsync -avzc --exclude=install --exclude=hypr --exclude=sway --exclude=README.md ./* ~/.config

if [ "$wm" == "sway" ]; then
   rsync -avcz ./sway ~/.config
else
    rsync -avcz ./hypr ~/.config
fi
#############################################
#            REBOOT SYSTEM                  #
#############################################

printf "Base installation done, time to rice it up.
System will now reboot...
"
reboot
