#!/usr/bin/env bash
# Script Name   : install
# Author        : Sébastien Gordano
# Date          : 07/2023
# Version       : 0.2
# Usage         : bash install
# Description   : Install / configure the basics for the use of WM on Arch linux
#===========================================================================
printf "
   ___                  _                 
  / _ \ _ __   __ _  __| |_ __ ___   __ _ 
 | | | | '_ \ / _' |/ _' | '__/ _ \ / _' |
 | |_| | | | | (_| | (_| | | | (_) | (_| |
  \___/|_| |_|\__,_|\__,_|_|  \___/ \__, |
       | | | | ___| |_ __   ___ _ __|___/ 
       | |_| |/ _ \ | '_ \ / _ \ '__|     
       |  _  |  __/ | |_) |  __/ |        
       |_| |_|\___|_| .__/ \___|_|        
                    |_|                   \n"
printf "Oi mate, Welcome to Onadrog's helper !\n\n"
printf 'Are ya running a laptop ?\n'
PS3='Make a choice (e.g: 1): '
options=("Yes" "No")

select opt in "${options[@]}"
do
  is_laptop="$opt"
  break;
done



#############################################
#                WM CHOICE                  #
#############################################
printf "
  ____  _      _                                           _                 
 |  _ \(_) ___| | __  _   _  ___  _   _ _ __   _ __   ___ (_)___  ___  _ __  
 | |_) | |/ __| |/ / | | | |/ _ \| | | | '__| | '_ \ / _ \| / __|/ _ \| '_ \ 
 |  __/| | (__|   <  | |_| | (_) | |_| | |    | |_) | (_) | \__ \ (_) | | | |
 |_|   |_|\___|_|\_\  \__, |\___/ \__,_|_|    | .__/ \___/|_|___/\___/|_| |_|
                      |___/                   |_|                            \n"

PS3='Make a choice(e.g: 1): '
options=("sway" "hyprland")

select opt in "${options[@]}"
do
    wm="$opt"
    break;
done

#############################################
#               BASIC INSTALL               #
#############################################

sudo pacman -Syu --noconfirm \
    brightnessctl vlc streamlink \
    playerctl neovim reflector \
    cups docker util-linux \
    ufw keepassxc swaylock swayidle \
    base-devel zsh nodejs npm pnpm \
    pcmanfm waybar \
    wl-clipboard otf-font-awesome gammastep \
    dnscrypt-proxy chezmoi \
    polkit-kde-agent firefox wofi \
    htop lightdm lightdm-gtk-greeter
   
if [ "$is_laptop" == "Yes" ]; then
    sudo -S --noconfirm tlp upower
fi

if [ "$wm" == "sway" ]; then
    sudo pacman -S --noconfirm \
        sway xdg-desktop-portal-gtk \
        xdg-desktop-portal-wlr swaybg foot
else
    sudo pacman -S --noconfirm \
        hyprland qt5-wayland xdg-desktop-portal-hyprland \
        hyprpaper kitty
fi

#############################################
#             INSTALL AUR HELPER            #
#############################################

printf "Choose an AUR helper from the list: \n"
PS3='Make a choice: (e.g: 1, 2)'
options=("yay" "paru") 

select opt in "${options[@]}"
do
    printf 'Installing %s helper\n' "$opt"
    sudo pacman -S --noconfirm --needed base-devel
    git clone https://aur.archlinux.org/"${opt}".git
    cd "$opt" || exit
    makepkg -si
    printf '%s installed\n' "$opt"
    cd || exit
    break;
done


#############################################
#               DNSCRYPT SERVICES           #
#############################################


sudo printf "nameserver 127.0.0.1
nameserver ::1
options edns0
" | tee /etc/resolv.conf && chattr +i /etc/resolv.conf

#############################################
#               SYSTEMD SERVICES            #
#############################################

printf 'Enabling systemd services...\n'

sudo systemctl enable reflector.timer cups.service fstrim.service docker.service ufw.service NetworkManager.service dnscrypt-proxy.service lightdm.service

if [ "$is_laptop" == "Yes" ];
then
  sudo systemctl enable tlp upower
fi

#############################################
#                CONF SHELL                 #
#############################################

printf "alias clean='sudo pacman -Qtdq | sudo pacman -Rns -'
export EDITOR='nvim'
" | tee ~/.bashrc

#############################################
#            COPY CONF FILES                #
#############################################

rsync -avzc --exclude=install --exclude=greetd --exclude=README ./* ~/.config

if [ "$wm" == "Sway" ]; then
   cp -r ./greetd ~/.config
fi
#############################################
#            REBOOT SYSTEM                  #
#############################################

printf "Base installation done, time to rice it up.
System will now reboot...
"
reboot
